const CatPics = [
  {
    breeds: [],
    id: '6s4',
    url: 'https://cdn2.thecatapi.com/images/6s4.jpg',
    width: 1024,
    height: 769,
  },
  {
    breeds: [],
    id: '9pk',
    url: 'https://cdn2.thecatapi.com/images/9pk.jpg',
    width: 525,
    height: 700,
  },
  {
    breeds: [],
    id: 'aqg',
    url: 'https://cdn2.thecatapi.com/images/aqg.jpg',
    width: 500,
    height: 582,
  },
  {
    breeds: [],
    id: 'cbi',
    url: 'https://cdn2.thecatapi.com/images/cbi.jpg',
    width: 820,
    height: 832,
  },
  {
    breeds: [],
    id: 'MTYwODQ4OQ',
    url: 'https://cdn2.thecatapi.com/images/MTYwODQ4OQ.jpg',
    width: 1087,
    height: 805,
  },
  {
    breeds: [],
    id: 'MTgxNzI5OQ',
    url: 'https://cdn2.thecatapi.com/images/MTgxNzI5OQ.jpg',
    width: 480,
    height: 480,
  },
  {
    breeds: [],
    id: 'MTkzNzI0MQ',
    url: 'https://cdn2.thecatapi.com/images/MTkzNzI0MQ.jpg',
    width: 3072,
    height: 2304,
  },
  {
    breeds: [],
    id: 'MjA4ODM4NA',
    url: 'https://cdn2.thecatapi.com/images/MjA4ODM4NA.jpg',
    width: 900,
    height: 779,
  },
  {
    breeds: [
      {
        weight: {
          imperial: '8 - 16',
          metric: '4 - 7',
        },
        id: 'norw',
        name: 'Norwegian Forest Cat',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/NorwegianForestCat.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/norwegian-forest-cat',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/norwegian-forest-cat',
        temperament:
          'Sweet, Active, Intelligent, Social, Playful, Lively, Curious',
        origin: 'Norway',
        country_codes: 'NO',
        country_code: 'NO',
        description:
          'The Norwegian Forest Cat is a sweet, loving cat. She appreciates praise and loves to interact with her parent. She makes a loving companion and bonds with her parents once she accepts them for her own. She is still a hunter at heart. She loves to chase toys as if they are real. She is territorial and patrols several times each day to make certain that all is fine.',
        life_span: '12 - 16',
        indoor: 0,
        alt_names:
          'Skogkatt / Skaukatt, Norsk Skogkatt / Norsk Skaukatt, Weegie',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 4,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Norwegian_Forest_Cat',
        hypoallergenic: 0,
        reference_image_id: '06dgGmEOV',
      },
    ],
    id: 'bsr5KQSJ6',
    url: 'https://cdn2.thecatapi.com/images/bsr5KQSJ6.jpg',
    width: 2000,
    height: 1331,
  },
  {
    breeds: [],
    id: 'R4KMmx2gb',
    url: 'https://cdn2.thecatapi.com/images/R4KMmx2gb.png',
    width: 1332,
    height: 674,
  },
];

export default CatPics;
